### ISSUE TITLE
missing error handling for type 'array'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#18] opened 2016-11-15 18:18 UTC
As an example, query parameter `screens` is defined like this in initialize-globals.js:

```js
    // Specifies the set of screens that appear in the sim, and their order.  Uses 1-based (not zero-based) and ","
    // delimited string such as "1,3,4" to get the 1st, 3rd and 4th screen.
    screens: {
      type: 'array',
      elementSchema: {
        type: 'number'
      },
      defaultValue: null
    },
```

If I do `?screens` with no arg, then QueryStringMachine fails at line 200, with "Cannot read property 'split' of null":

```js
198    var stringToArray = function( key, string, schema ) {
199      queryStringMachineAssert( schema.elementSchema, key, 'array element schema must be defined' );
200      return string.split( schema.separator || DEFAULT_SEPARATOR ).map( function( element ) {
201        return parseElement( key, schema.elementSchema, [ element ] );
202      } );
 202   };
```

Looks like we need to add this assertion before line 199:

```js
 queryStringMachineAssert( string, key, 'missing value' );
```

**Comment by pixelzoom** [comment] 2016-11-15 18:23
Fixed, @samreid please review.

**Comment by samreid** [comment] 2016-11-16 19:23
This may be at odds with #17

**Comment by samreid** [comment] 2016-11-19 04:51
After adding support for 0-length arrays in #17, it seemed we should default the screens query parameter to [] instead of null.  I tested this and it seems to be working well.  Committing.

**Comment by samreid** [comment] 2016-11-19 04:54
Committed above and tested with ?screens, ?screens=, ?screens=1, ?screens=2, ?screens=1,2 and all behaved as expected.  My only qualm is that ?screens is parsed identically to ?screens=.  I'd rather require the = sign in order to specify an empty array, but it would require changes to the QSM logic than I'd rather not change, so the current behavior is acceptable to me.

@pixelzoom would you like to review?

**Comment by pixelzoom** [comment] 2016-11-21 19:10
I'm unclear on what is "expected" with `?screens` and `?screens=`.  When use either of those (e.g. with graphing-lines), it shows me all screens, as if the query parameter is not present.  Please clarify.

**Comment by samreid** [comment] 2016-11-22 03:35
I changed the joist semantics so that an empty array means to show all screens.

**Comment by pixelzoom** [comment] 2016-11-22 03:41
I agree that in general an empty array should be supported. I don't agree that an empty array should be valid for `screens`, or that joist should interpret and empty array as "all screens".

**Comment by samreid** [comment] 2016-11-22 03:42
Is `null` better than `[]` for denoting to show all screens?  If so, why?

**Comment by pixelzoom** [comment] 2016-11-22 03:43
If you want to show all screen, then you have 2 very valid, logical choices: (1) don't use the `screens` query parameter, or (2) use the `screens` query parameter with an array that includes all screen indices.

**Comment by samreid** [comment] 2016-11-22 03:44
I see, Joist can check if `QueryStringMachine.containsKey('screens')` and then use that.

**Comment by pixelzoom** [comment] 2016-11-22 03:44
Yes.

**Comment by samreid** [comment] 2016-11-22 16:02
Added test above, now ?screens and ?screens= are failing, and ?screens=1,2 and ?screen=3 are working, and lint is passing.  @pixelzoom want to review?

**Comment by pixelzoom** [comment] 2016-11-22 18:45
Client code fix looks good.  But I think we still have some work to do on QueryStringMachine.

In initialize-globals.js, `screens` schema is currently:

```js
    screens: {
      type: 'array',
      elementSchema: {
        type: 'number'
      },
      defaultValue: []
    },
```

The lack of support for `defaultValue: null` is presumably why you need to specify `defaultValue: []`.  And that's kind of like having to specify `defaultValue: ''` for 'string' type.  So, like 'string' type, I think we should support `null` as a valid `defaultValue` for type 'array'.

**Comment by samreid** [comment] 2016-11-22 22:23
QSM does support null as a defaultValue for type array, I can switch back to it.

**Comment by pixelzoom** [comment] 2016-11-22 22:29
I tried switching the schema for `screens` back to `defaultValue: null`, but then I see:

```
> phet.chipper.queryParameters.screens
[]
```

**Comment by samreid** [comment] 2016-11-22 22:35
Testing...

**Comment by samreid** [comment] 2016-11-22 22:37
I changed screens to read:

```js
    screens: {
      type: 'array',
      elementSchema: {
        type: 'number'
      },
      defaultValue: null
    },
```

Then put this line at 68 of Sim.js
```js
console.log(phet.chipper.queryParameters.screens);
```

Then I ran the sim, and it printed out:
`null`.

![image](https://cloud.githubusercontent.com/assets/679486/20544899/8763571a-b0c9-11e6-8fbf-87b673787a3c.png)

How are you arriving at your result?

**Comment by pixelzoom** [comment] 2016-11-22 22:57
Confirmed. Browser must've been caching initialize-globals.js, perhaps because it's a preload.

**Comment by samreid** [comment] 2016-11-22 22:57
My best way to prevent browser cache is to run with dev tools open, and this setting selected:

![image](https://cloud.githubusercontent.com/assets/679486/20545434/6c289fde-b0cc-11e6-8e5f-6a95991c0728.png)

**Comment by pixelzoom** [comment] 2016-11-22 23:07
Got it. Chrome, dev tools, 'Network' tab, 'Disable cache' check box.

![screenshot_81](https://cloud.githubusercontent.com/assets/3046552/20545703/d03d73e0-b0cd-11e6-9d45-35663408307f.png)

**Comment by samreid** [comment] 2016-11-23 04:35
Yes, I confirmed that Network => disable cache is synchronized with Settings => "Disable cache (while DevTools is open)".  Anything else to do here?

**Comment by pixelzoom** [comment] 2016-11-23 18:22
We appear to be done. Closing.

**Comment by pixelzoom** [comment] 2016-11-23 20:46
Reopening. 

In https://github.com/phetsims/query-string-machine/issues/18#issuecomment-262386981, @samreid indicated that he changed `defaultValue: null` for `screens`.  But I don't see that committed, I still see `defaultValue: []`.  I'll change it.

**Comment by pixelzoom** [comment] 2016-11-23 20:49
Done. @samreid please review.

**Comment by samreid** [comment] 2016-11-24 17:22
Looks good, thanks!  Closing.

**Closed by samreid** 2016-11-24 17:22 UTC
