### ISSUE TITLE
rewrite QueryStringMachine

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/query-string-machine#20] opened 2016-11-23 23:18 UTC
This issue started its life as https://github.com/phetsims/query-string-machine/issues/19, but grew.

I'm proposing to rewrite QueryStringMachine, or at least do a major cleanup.

In https://github.com/phetsims/query-string-machine/issues/19#issuecomment-262598021, I noted:
> Looking more closely at the current state of QueryStringMachine... There's a lot of conditional logic in validateSchema and parseElement. And it's difficult to make a change (e.g. phetsims/chipper#519) to the behavior of one type without affecting others. We could improve the readability and maintainability by breaking things up into type-specific validation and parsing functions. E.g., validateFlag and parseFlag, validateBoolean and parseBoolean, etc.

If we were to split things up as described above, it would be relative easy to modify a type without affecting other types, or to add an entirely new type.

Other issues noted:
• Documentation about what schema fields are required/optional is incorrect.
• It's difficult to see what fields are required vs optional for each type.
• There is a significant amount of type-specific validation missing, especially for type 'array'.
• The bit of validation that does exist for type 'array' relies on `JSON.stringify`, which is documented as providing no guarantee about the order of fields.
• Validation is entirely missing for when the `parse` property (mutually exclusive with `type`) is present.
• The way `assert` is defined doesn't help us in PHET sims. QueryStringMachine is loaded before initialize-globals.js, where `window.assert` is defined.

**Comment by pixelzoom** [comment] 2016-11-23 23:22
I pushed QueryStringMachine2 to demonstrate the approach that I had in mind.  It's working in sims, but is still failing a couple of automated tests.  @samreid let's discuss after the holiday.

**Comment by pixelzoom** [comment] 2016-11-23 23:24
Most of the TODO items in QueryStringMachine2 identify problems that are also present in QueryStringMachine.

**Comment by samreid** [comment] 2016-11-24 01:47
Some thoughts:

(1) We should add a "custom" type, like so:

```js
      custom: {
        required: [ 'parse' ],
        optional: [ 'defaultValues', 'validValues' ]
      }
```

Then its error checking will fit into the rest of the pattern.

(2) We should add validate and parse methods in the type descriptors, it would be something like this:

```js
    var TYPES = {

      flag: {
        required: [ 'type' ],
        optional: [],
        parse:function(string){...},
        validate: function(...){...}
      },

      boolean: {
        required: [ 'type' ],
        optional: [ 'defaultValue' ],
        parse: function(){...},
        validate:function(...){...}
      },
```
This will help us organize the types.

**Comment by pixelzoom** [comment] 2016-11-25 16:21
Both excellent suggestions. Me likey.

**Comment by pixelzoom** [comment] 2016-11-28 17:10
Rather than put the implantation of the functions in the `TYPES` data structure, how about just the function name?  E.g.:

```js
var TYPES = {

      flag: {
        required: [ 'type' ],
        optional: [],
        validate: validateFlag,
        parse: parseFlag

      },

      boolean: {
        required: [ 'type' ],
        optional: [ 'defaultValue' ],
        validate:validateBoolean,
        parse: parseBoolean   
      },
      ...
```

**Comment by pixelzoom** [comment] 2016-11-28 17:45
I implemented @samreid's suggestions in QueryStringMachine2. Not rigorously tested.

**Comment by pixelzoom** [comment] 2016-11-28 21:36
Looks like replacing `parse` with `type: 'custom'` only affects testQueryStringMachine.js.  I don't see any clients using `parse` yet.

**Comment by pixelzoom** [comment] 2016-11-28 23:10
QueryStringMachine2 is passing all tests in testQueryStringMachine.js.  I would suggest replacing QueryStringMachine with QueryStringMachine2, but I have very little faith in the completeness or robustness of testQueryStringMachine.js (based on my deep dive in #24).

**Comment by samreid** [comment] 2016-11-29 03:58
Let's go for QueryStringMachine2.  I'll merge it, delete QueryStringMachine2, test what I can and we'll move forward from here.

**Comment by samreid** [comment] 2016-11-29 04:01
Merged in the preceding commit, tests are passing.  Main sim development mode like "brand=phet&ea" is working.

**Comment by samreid** [comment] 2016-11-29 04:43
I emailed the development list:

Chris and I (but mostly Chris) updated the implementation of QueryStringMachine as part of https://github.com/phetsims/query-string-machine/issues/20.  Basic tests are passing, but please be on the lookout for unexpected behavior.

Best Regards,
Sam

**Comment by samreid** [comment] 2016-11-29 04:48
Aqua tests are passing (I limited my run to faradays-law):

![image](https://cloud.githubusercontent.com/assets/679486/20697183/54153ca8-b5b4-11e6-98ad-45b1518d2c51.png)

Anything else specific to do or test here?  Or just address new problems as they arise?

**Comment by samreid** [comment] 2016-11-29 04:52
I'm seeing many TODO's, I'll take a look before giving this back to @pixelzoom.

**Comment by samreid** [comment] 2016-11-29 05:23
In the preceding commit, I made defaults optional for all types.  If there is no default, and no value provided in the query string, an error is thrown.

**Comment by pixelzoom** [comment] 2016-11-29 05:31
> If there is no default, and no value provided in the query string, an error is thrown.

Doesn't that effectively make `defaultValue` required? I don't understand the motivation for making it optional.

The preceding commit also makes `elemetSchema` optional for type 'array'.  How do we know the type of the elements? Or are you assuming that elements are of type 'string' if there is no `elementSchema`?

**Comment by pixelzoom** [comment] 2016-11-29 05:40
I really think that `defaultValue` should be required for type 'number'.

For the other types, if it's optional then perhaps there should be a fallback default value (as we have now for 'boolean').  E.g.:

boolean: true
string: null
array: null
custom: null

**Comment by samreid** [comment] 2016-11-29 05:43
> Doesn't that effectively make `defaultValue` required? I don't understand the motivation for making it optional.

For instance, imagine a webpage that requires a `sessionID` to be passed as a query parameter.  If you launch the page without providing `?sessionID=something`, then the page should error out.

**Comment by samreid** [comment] 2016-11-29 05:43
> The preceding commit also makes `elemetSchema` optional for type 'array'.  How do we know the type of the elements? Or are you assuming that elements are of type 'string' if there is no `elementSchema`?

My mistake, I restored it in https://github.com/phetsims/query-string-machine/commit/100a57d8ede24585fe244c9df85d8e6f00c87fe9

**Comment by samreid** [comment] 2016-11-29 05:45
> If you launch the page without providing `?sessionID=something`, then the page should error out.

**And** provide a helpful error message in the console that the `sessionID` must be provided as a query parameter.

**Comment by pixelzoom** [comment] 2016-11-29 05:50
> imagine a webpage that requires a `sessionID`

I thought that we discussed "required" query parameter, and decided that they should be handled like this:

```js
if ( !QueryStringMachine.containsKey( 'sessionID' ) ) {
  throw new Error(...);
}
```

**Comment by samreid** [comment] 2016-11-29 06:01
> I thought that we discussed "required" query parameter,

My apologies, my memory of the discussion is fuzzy.

> decided that they should be handled like this:

That seems like a great way to provide application-specific support for missing query parameters (such as showing a custom UI alerting the user of the problem).  But for cases where a query parameter is required, it seems convenient for QueryStringMachine to automatically check for it.  For instance, in Recorder.js, there is this code:

```js
      // All required
      metacogParameters = QueryStringMachine.getAll( {
        publisher_id: {
          type: 'string'
        },
        application_id: {
          type: 'string'
        },
        widget_id: {
          type: 'string'
        },
        learner_id: {
          type: 'string'
        }
      } );
```

If we changed it to the pattern in https://github.com/phetsims/query-string-machine/issues/20#issuecomment-263482783 it would look something more like:

```js
      // All required
      metacogParameters = QueryStringMachine.getAll( {
        publisher_id: {
          type: 'string',
          defaultValue: null
        },
        application_id: {
          type: 'string',
          defaultValue: null
        },
        widget_id: {
          type: 'string',
          defaultValue: null
        },
        learner_id: {
          type: 'string',
          defaultValue: null
        }
      } );

      assert && assert( QueryStringMachine.containsKey( 'publisher_id' ), 'the publisher_id must be supplied' );
      assert && assert( QueryStringMachine.containsKey( 'application_id' ), 'the application_id must be supplied' );
      assert && assert( QueryStringMachine.containsKey( 'widget_id' ), 'the widget_id must be supplied' );
      assert && assert( QueryStringMachine.containsKey( 'learner_id' ), 'the learner_id must be supplied' );
```

The former is superior because it avoids extraneous duplication of the key names.

**Comment by samreid** [comment] 2016-11-29 06:35
In the above commit I added validation for array elementSchemas, and it showed me another place we are assuming `defaultValues` are provided.  I committed the above commit to make things consistent, not because https://github.com/phetsims/query-string-machine/issues/20#issuecomment-263484209 is a foregone conclusion.  If we decide to make defaults required, then we should undo the change in the preceding commit.

**Comment by pixelzoom** [comment] 2016-12-01 18:24
Discussed with @samreid, summary:

(1) If a query parameter is required, don't specify `defaultValue` and QueryStringMachine will error out if query parameter is not present.
(2) If a query parameter is not required, specify `defaultValue`.
(3) 1 & 2 apply to all types except 'flag'.
(4) We'll need to change the behavior of 'boolean', which current falls back to `true` if `defaultValue` is not specified.

**Comment by pixelzoom** [comment] 2016-12-01 18:37
(5) Factor out `validateValue` from `parse`, add to TYPES data structure.

**Comment by pixelzoom** [comment] 2016-12-01 20:10
1-4 above addressed, unit tests passing, test-server passing.

**Comment by pixelzoom** [comment] 2016-12-01 20:28
@samreid FYI, I'm mostly done with 5 above (so we don't duplicate work).

**Comment by samreid** [comment] 2016-12-01 21:26
Thanks, please reassign to me if you'd like a review afterwards.

**Comment by pixelzoom** [comment] 2016-12-01 22:54
Item 5 above (factor out `validateValue`) resulted in lots of changes, see above commit.  I ran unit tests and did spot-testing of a few sims.

A few things to note:
• validateSchema is now optional, since (for most types) it can be handled in a general way
• I noticed that lodash is now used for deep comparison (`_.isEqual`). Is that compatible with the requirement of making `QueryStringMachine` "capable of working everywhere"?
• I added a few TODO items that require further discussion.

Back to @samreid.

**Comment by pixelzoom** [comment] 2016-12-05 17:31
Use of lodash was removed in #25.

**Comment by pixelzoom** [comment] 2016-12-05 18:07
Here are the remaining TODO items that need to be discussed:

```js
41 //TODO how is assert useful here? window.assert isn't defined until after QSM is loaded.
385 //TODO do we need to add a property to 'custom' schema that handles validation of custom value?
```

**Comment by samreid** [comment] 2016-12-08 06:30
I addressed the 1st TODO.  For the 2nd TODO, my opinion is to leave it unimplemented until we need it (if ever).

**Comment by pixelzoom** [comment] 2016-12-08 15:02
I guess my question about `assert` wasn't clear. `assert` will always be undefined until `QueryStringMachine.getAll` is run in initialize-globals.js, so why are we using `assert` within the implementation of `QueryStringMachine`?

**Comment by samreid** [comment] 2016-12-08 17:16
> So why are we using `assert` within the implementation of `QueryStringMachine`?  

Here is the code:

```js
      getForString: function( key, schema, string ) {

        // Uses window.assert in the browser, and global.assert in node
        assert && assert( string.length === 0 || string.indexOf( '?' ) === 0, 'Query strings should be either the ' +
                                                                              'empty string or start with a "?": ' +
                                                                              string );
        validateSchema( key, schema );
        var value = parseValues( key, schema, getValues( key, string ) );
        validateValue( key, schema, value );
        return value;
      }
```

I used assert instead of queryStringMachineAssert because this problem indicates an issues with coding, not with supplied user parameters.  But I would be equally happy (happier?) to change this to a thrown Error instead of an assert (because assert introduces a dependency).  Thoughts?

**Comment by pixelzoom** [comment] 2016-12-08 17:47
I agree that an assertion (vs an Error) is appropriate here, because it's a programming error.  But regardless of whether the `?ea` query parameter is provided in a sim URL, `assert` is `null` in QueryStringMachine, because assertions are enabled/disabled as the result of processing query parameters with QueryStringMachine.  So any code prefixed by `assert &&` will never be executed, regardless of whether `?ea` is specified.  So my point is that `assert` *cannot* be used in QueryStingMachine.

**Comment by samreid** [comment] 2016-12-08 18:07
I see, thanks for pointing out that ordering.  I'll throw an error instead.

**Comment by pixelzoom** [comment] 2016-12-08 18:17
I think that `throw Error` will be fine (versus `queryStringMachineAssert`).

**Comment by pixelzoom** [comment] 2016-12-08 18:20
I took care of it (converted assert to Error).

@samreid Anything else to do here?

**Comment by samreid** [comment] 2016-12-08 18:24
Looks great, closing.

**Closed by samreid** 2016-12-08 18:24 UTC
